import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [busy, setBusy] = useState(false);
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ul style={{ opacity: busy ? 0.5 : 1, transition: "opacity 500ms" }}>
          <li>
            <button
              onClick={async () => {
                setBusy(true);

                const result = await router.push("/page-2");

                console.log("`router.push` resolved to", result);

                setBusy(false);
              }}
            >
              router.push
            </button>
          </li>
          <li>
            <button
              onClick={async () => {
                setBusy(true);

                await router.prefetch("/page-2");

                console.log("`router.prefetch` resolved");

                setBusy(false);
              }}
            >
              router.prefetch
            </button>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
